import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import "@fontsource/orbitron";
import SiteChrome from "@/components/SiteChrome";

export const metadata: Metadata = {
  title: "F1 News",
  description: "Generated by Elalj Mohamed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SiteChrome>
        <header className="w-full h-20 p-12 flex items-center relative">
          <Link href="/" className="absolute left-50">  <img src="/f1-logo.png" alt="F1 logo" className=" w-40 h-40" /> </Link>
           <nav className="flex justify-center gap-18 text-xl mx-auto">
            <Link href="/news" className="hover:text-gray-300 font-f1 text-2xl">News</Link>
            <Link href="/drivers" className="hover:text-gray-300 font-f1 text-2xl">Drivers</Link>
            <Link href="/schedule" className="hover:text-gray-300 font-f1 text-2xl">Schedule</Link>
            <Link href="/standings" className="hover:text-gray-300 font-f1 text-2xl">Standings</Link>
            <Link href="/circuits" className="hover:text-gray-300 font-f1 text-2xl">Circuits</Link>
           </nav>
        </header>
            {children}
        </SiteChrome> 
        <footer className="fixed bottom-10 h-35 w-180 rounded-xl overflow-hidden z-50">
          {/* Header / Title */}
          <div className="text-white/70 text-center font-f1 tracking-widest text-2xl px-4 py-4 font-bold">
            What's on you mind Pilot ?
          </div>
         {/* Input */}
          <div className="flex p-2 bg-white/50 rounded-xl">
            <input
              type="text"
              placeholder="Ask me anything..."
              className="flex-1 px-4 py-1 outline-none text-black text-xl"
              />
            <button className="bg-black/20 text-white/70 rounded-xl px-4">Send</button>
          </div>
        </footer>
      </body>
    </html>
  );
}
